apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-openshift-ingress
  namespace: your-namespace
spec:
  podSelector: {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          openshift.io/cluster-ingress: "true"
    ports:
    - protocol: TCP
      port: 80